---
driver:
  name: docker 
  socket: <%= ENV['DOCKER_HOST'] %>
driver_config:
  require_chef_omnibus: true
busser:
  sudo: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04

suites:
- name: default
  run_list: 
    - "recipe[graphite-wrapper::default]"
  attributes:
